name = "different-proofs"
version = "0.1.0"
defaultTargets = ["DifferentProofs"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.flexible = false

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "f746499f9d3c829cdb29e0629ce2ed4ecfc0e2ac"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.29.1"

[[lean_lib]]
name = "DifferentProofs"
