name: Lean Action CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
      - name: Run mk_all and error if changed
        if: github.event_name == 'pull_request'
        run: |
          lake exe mk_all --lib DifferentProofs --module && exit 0
          echo "mk_all reported changes"
          echo 'Please run `lake exe mk_all --lib DifferentProofs --module` to fix'
          exit 1
